### ISSUE TITLE
panics in library

### ISSUE THREAD

**Issue by kgilmer** [orhun/runst#87]
Hi! This issue is created as directed by `CONTRIBUTING.md`.  First, I'm new to rust and found your freedesktop notification server very helpful as a project to hack on while learning the language.  I am working on a fork for a DE that provides a different UI treatment for notifications.  During testing I've noticed that if another notification dbus server is running, the service starts but does nothing.  IMO better behavior would be to [abort at this point](https://github.com/kgilmer/armesto/blob/main/src/dbus.rs#L158-L160).  I'd be happy to create a PR to add this to `runst` if you agree.  I'd also be curious to know you reasoning if you think `runst` should not abort under this scenario.

:peace_symbol:

**Comment by orhun** [comment]
Hello!

This would be a fair thing to implement I think.

>  I'd also be curious to know you reasoning if you think runst should not abort under this scenario.

I think I haven't really thought about this case 😅 

> I'd be happy to create a PR

Please go ahead!

**Comment by kgilmer** [comment]
Ready for review at your convenience @orhun :tulip:
